### ISSUE TITLE
Restore minimap stopped working on gedit 42.0

### ISSUE THREAD

**Issue by cg00001** [johnfactotum/gedit-restore-minimap#7]
Using Arch Linux.

**Comment by johnfactotum** [comment]
You don't need this plugin anymore on gedit 42. It has reverted pretty much all changes made since 3.36 and brought back the minimap. See https://github.com/johnfactotum/gedit-restore-minimap/issues/6#issuecomment-919920121.

**Comment by cg00001** [comment]
I didn't use overview map in the past, so I had to look for it in Preferences, thank you.
![23](https://user-images.githubusercontent.com/38960370/165039845-79ff4510-49ab-4d0c-bfee-1e37dd6ec94e.png)
